In [1]:
#import pyabc
from pyabc import *
import json
import numpy as np

In [2]:
#pyabc.

In [3]:
ts_tunes = json.loads(open('thesession_2017_07_12.json', 'rb').read().decode('utf8'))


In [4]:
ts_tunes[3]

{u'abc': u'eAAB eABB|eAAB gedB|eAAB eABB|G2AB gedB:|\r\n~e3d efg2|~e3f gedB|~e3d efg2|G2AB gedB|\r\n~e3d efg2|~e3f gedB|efga geg2|GABG gedB||',
 u'date': u'2015-07-31 02:47:47',
 u'meter': u'4/4',
 u'mode': u'Bminor',
 u'name': u"'S Daor An Tabac",
 u'setting': u'26955',
 u'tune': u'14625',
 u'type': u'reel',
 u'username': u'Charles Mackenzie'}

In [5]:
def matchJsonField(js,field,string):
    result = []
    for t in js:
        if t[field] == string:
            result.append(t)
    return  result  

def inJsonField(js,field,string):
    result = []
    for t in js:
        if string in t[field]:
            result.append(t)
    return result

def fieldList(js,field):
    result = []
    for t in js:
        result.append(t[field])
    return result
        

In [6]:
result = matchJsonField(ts_tunes,'name','Banish Misfortune')
print result

[{u'username': u'Jeremy', u'abc': u'fed cAG| A2d cAG| F2D DED| FEF GFG|\r\nAGA cAG| AGA cde|fed cAG| Ad^c d3:|\r\nf2d d^cd| f2g agf| e2c cBc|e2f gfe| \r\nf2g agf| e2f gfe|fed cAG|Ad^c d3:|\r\nf2g e2f| d2e c2d|ABA GAG| F2F GED|\r\nc3 cAG| AGA cde| fed cAG| Ad^c d3:|', u'name': u'Banish Misfortune', u'meter': u'6/8', u'setting': u'9', u'mode': u'Dmixolydian', u'date': u'2001-05-18 03:50:35', u'type': u'jig', u'tune': u'9'}, {u'username': u'JACKB', u'abc': u'gfe dBA| B2e dBA| G2E EFE| GFG AGA|\r\nBAB dBA| BAB def|gfe dBA| Be^d e3:|\r\ng2e e^de| g2a bag| f2d dcd|f2g agf|\r\ng2a bag| f2g agf|gfe dBA|Be^d e3:|\r\ng2a f2g| e2f d2e|BcB ABA| G2G AFE|\r\nd3 dBA| BAB def| gfe dBA| Be^d e3:|', u'name': u'Banish Misfortune', u'meter': u'6/8', u'setting': u'22361', u'mode': u'Emixolydian', u'date': u'2013-09-24 07:09:32', u'type': u'jig', u'tune': u'9'}, {u'username': u'GaryAMartin', u'abc': u'd2 e|fed cAG|A2d =cAG|EFD DdD|FDF GFG|\r\nA^GA =cAD|(3EFG A cde|fed cAG|AdA d2 g||\r\nfed cAG|A2d =cAG|EFD 

In [7]:
result = inJsonField(ts_tunes,'name','Hag')
print fieldList(result,'name')
print fieldList(result,'type')
print fieldList(result,'mode')

[u'Back Of The Haggard, The', u'Back Of The Haggard, The', u'Back Of The Haggard, The', u'Back Of The Haggard, The', u'Cheer Up Old Hag', u'Cheer Up Old Hag', u'Cheer Up Old Hag', u'Cheer Up Old Hag', u'Cheer Up Old Hag', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Churn, The', u'Hag At The Spinning Wheel, The', u'Hag At The Spinning Wheel, The', u'Hag At The Spinning Wheel, The', u'Hag At The Spinning Wheel, The', u'Hag At The Spinning Wheel, The', u'Hag At The Spinning Wheel, The', u'Hag By The Fire, The', u'Hag By The Fire, The', u'Hag With No Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u'Hag With The Money, The', u"Hag's Dream, The", u"Hag's Dream, The", u"Hag's Dream, Th

In [8]:
t = matchJsonField(ts_tunes,'name','Banish Misfortune')[0]
tune = Tune(json=t)


fed cAG| A2d cAG| F2D DED| FEF GFG|
AGA cAG| AGA cde|fed cAG| Ad^c d3:|
f2d d^cd| f2g agf| e2c cBc|e2f gfe| 
f2g agf| e2f gfe|fed cAG|Ad^c d3:|
f2g e2f| d2e c2d|ABA GAG| F2F GED|
c3 cAG| AGA cde| fed cAG| Ad^c d3:|


In [9]:
tune.header

{'key': u'Dmixolydian',
 'meter': u'6/8',
 'reference number': u'9',
 'setting': u'9',
 'tune title': u'Banish Misfortune',
 'unit note length': u'1/8'}

In [10]:
note = tune.notes[1]

In [11]:
key = Key(name=tune.header['key'])
key.relative_ionian

<Key G ionian>

In [12]:
tune.tokens

[<Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A2">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "F2">,
 <Note "D">,
 <Space " ">,
 <Note "D">,
 <Note "E">,
 <Note "D">,
 <Beam "|">,
 <Space " ">,
 <Note "F">,
 <Note "E">,
 <Note "F">,
 <Space " ">,
 <Note "G">,
 <Note "F">,
 <Note "G">,
 <Beam "|">,
 <Newline "
 ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "d">,
 <Note "e">,
 <Beam "|">,
 <Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "d">,
 <Note "^c">,
 <Space " ">,
 <Note "d3">,
 <Beam ":|">,
 <Newline "
 ">,
 <Note "f2">,
 <Note "d">,
 <Space " ">,
 <Note "d">,
 <Note "^c">,
 <Note "d">,
 <Beam "|">,
 <Space "

In [13]:
tune.notes

[<Note "f">,
 <Note "e">,
 <Note "d">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Note "A2">,
 <Note "d">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Note "F2">,
 <Note "D">,
 <Note "D">,
 <Note "E">,
 <Note "D">,
 <Note "F">,
 <Note "E">,
 <Note "F">,
 <Note "G">,
 <Note "F">,
 <Note "G">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Note "c">,
 <Note "d">,
 <Note "e">,
 <Note "f">,
 <Note "e">,
 <Note "d">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Note "d">,
 <Note "^c">,
 <Note "d3">,
 <Note "f2">,
 <Note "d">,
 <Note "d">,
 <Note "^c">,
 <Note "d">,
 <Note "f2">,
 <Note "g">,
 <Note "a">,
 <Note "g">,
 <Note "f">,
 <Note "e2">,
 <Note "c">,
 <Note "c">,
 <Note "B">,
 <Note "c">,
 <Note "e2">,
 <Note "f">,
 <Note "g">,
 <Note "f">,
 <Note "e">,
 <Note "f2">,
 <Note "g">,
 <Note "a">,
 <Note "g">,
 <Note "f">,
 <Note "e2">,
 <Note "f">,
 <Note "g">,
 <Note "f">,
 <Note "e">,
 <Note "f">,
 <Note "e">,
 

In [14]:
note = tune.notes[6]
pitch = note.pitch

In [15]:
pitch.abs_value

9

In [16]:


def transposeKey(key0,step):
    from numpy import mod, floor_divide
    inv_pitch_values={ pitch_values[n]:n for n in chromatic_notes }


    mode = key0.mode
    rootval0 = pitch_values[key0.root.name] + step
    rootval = mod(rootval0,12)
    root = inv_pitch_values[rootval]
    
    return Key(root=root,mode=mode)
    

In [17]:
tune

In [18]:
tune.header['key']

u'Dmixolydian'

In [19]:
tune.tokens

[<Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A2">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "F2">,
 <Note "D">,
 <Space " ">,
 <Note "D">,
 <Note "E">,
 <Note "D">,
 <Beam "|">,
 <Space " ">,
 <Note "F">,
 <Note "E">,
 <Note "F">,
 <Space " ">,
 <Note "G">,
 <Note "F">,
 <Note "G">,
 <Beam "|">,
 <Newline "
 ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "d">,
 <Note "e">,
 <Beam "|">,
 <Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "d">,
 <Note "^c">,
 <Space " ">,
 <Note "d3">,
 <Beam ":|">,
 <Newline "
 ">,
 <Note "f2">,
 <Note "d">,
 <Space " ">,
 <Note "d">,
 <Note "^c">,
 <Note "d">,
 <Beam "|">,
 <Space "

In [20]:
def isNote(x):
    return isinstance(x,Note)

def isBeam(x):
    return isinstance(x,Beam)

def simplifyTokens(tokens):
    '''
    Removes any elements that aren't notes or bars.
    '''
    results = []
    for t in tokens:
        if isNote(t) or isBeam(t):
            results.append(t)
        else:
            pass
    return results

def findMeasures(tokens1):
    '''
    For now this requires that parts be repeating
    '''
    tokens = simplifyTokens(tokens1)
    result = []
    meas = []
    for t in tokens:
        if isBeam(t):
            meas.append(t)
            result.append(meas)
            meas = []
        else:
            meas.append(t)
    return result
            
        
def findParts(measures):
        
    result = []
    part = []
    for m in measures:
        if  ':|' in str(m[-1]):
            part.append(m)
            result.append(part)
            part = []
        else:
            part.append(m)
    return result
    
    

In [21]:
measures = findMeasures(tune.tokens)
measures

[[<Note "f">,
  <Note "e">,
  <Note "d">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A2">, <Note "d">, <Note "c">, <Note "A">, <Note "G">, <Beam "|">],
 [<Note "F2">, <Note "D">, <Note "D">, <Note "E">, <Note "D">, <Beam "|">],
 [<Note "F">,
  <Note "E">,
  <Note "F">,
  <Note "G">,
  <Note "F">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">,
  <Note "G">,
  <Note "A">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">,
  <Note "G">,
  <Note "A">,
  <Note "c">,
  <Note "d">,
  <Note "e">,
  <Beam "|">],
 [<Note "f">,
  <Note "e">,
  <Note "d">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">, <Note "d">, <Note "^c">, <Note "d3">, <Beam ":|">],
 [<Note "f2">, <Note "d">, <Note "d">, <Note "^c">, <Note "d">, <Beam "|">],
 [<Note "f2">, <Note "g">, <Note "a">, <Note "g">, <Note "f">, <Beam "|">],
 [<Note "e2">, <Note "c">, <Note "c">, <Note "B">, <Note "c">, <Beam "|">],
 [<Note "e2">, <Note "f">, <Note "g">, <Note "f">, <Note "

In [22]:
parts = findParts(measures)
print len(parts), 'parts'
for p in parts:
    print 2.*len(p), 'bars'

3 parts
16.0 bars
16.0 bars
16.0 bars


In [23]:
tune.tokens[13]

<Note "A">

In [24]:
incnote = 32
measure = measures[0]
meter = tune.header['meter']
key = Key(tune.header['key'])
beat_mult = float(meter.split('/')[0])
beat_value = float(meter.split('/')[1])
incdur = 1. * beat_value / incnote
print beat_mult, beat_value, incdur

lm = []
for x in measure:
    if isinstance(x,Note):
        #print x.pitch.value, x.duration, int(np.round(x.duration / incdur))
        ndigits = int(np.round(x.duration / incdur))
        lm += [x.pitch.value + 12.*x.pitch.octave for i in range(ndigits)]

marr = np.array(lm)


marr_abs = marr
marr_rel_root  = marr_abs - key.root.value
marr_rel_ionian = marr_abs - key.relative_ionian.root.value

print measure
print marr_abs
print marr_rel_root
print marr_rel_ionian

print np.mod(marr_abs,12.)

6.0 8.0 0.25
[<Note "f">, <Note "e">, <Note "d">, <Note "c">, <Note "A">, <Note "G">, <Beam "|">]
[ 18.  18.  18.  18.  16.  16.  16.  16.  14.  14.  14.  14.  12.  12.  12.
  12.   9.   9.   9.   9.   7.   7.   7.   7.]
[ 16.  16.  16.  16.  14.  14.  14.  14.  12.  12.  12.  12.  10.  10.  10.
  10.   7.   7.   7.   7.   5.   5.   5.   5.]
[ 11.  11.  11.  11.   9.   9.   9.   9.   7.   7.   7.   7.   5.   5.   5.
   5.   2.   2.   2.   2.   0.   0.   0.   0.]
[ 6.  6.  6.  6.  4.  4.  4.  4.  2.  2.  2.  2.  0.  0.  0.  0.  9.  9.
  9.  9.  7.  7.  7.  7.]


In [25]:
class digitizedTune(object):
    def __init__(self,json=None,tune=None,incnote=32):
        if json is not None:
            self.json = json
            pyabc.Tune(json=self.json)
            self.pyabcTune = tune
            
        if tune is not None:
            self.pyabcTune = tune
            self.tokens = tune.tokens
            
            measures = findMeasures(self.tokens)
            parts = findParts(measures)
            self.num_parts =  len(parts)
            la = []
            for p in parts:
                la.append( 2.*len(p)) # Note simplified version assumes repeating parts.
            
            self.bars = np.array(la) # array of number of bars for part
            self.total_bars = np.sum(self.bars)
            
            self.key = Key(tune.header['key'])
            self.meter = tune.header['meter']
            self.beat_mult = float(self.meter.split('/')[0])
            self.incnote = incnote
            self.incdur = 1. * beat_value / incnote
            
            dtune = []
            for p in parts:
                dpart = []
                for m in p:
                    dmeas = self.digitizeMeasure(m)
                    dpart.append(dmeas)
                    
                dtune.append(dpart)
            
            self.tune = dtune
            
    def part(self,n):
        assert n < self.num_parts
        return self.tune[n]

    def measure(self,np,nm):
        assert np < self.numparts
        assert nm < len(self.tune[np])
        return self.tune[np][nm]

        #incnote = 32
    def digitizeMeasure(self,measure):

        lm = []
        for x in measure:
            if isinstance(x,Note):
                #print x.pitch.value, x.duration, int(np.round(x.duration / incdur))
                ndigits = int(np.round(x.duration / self.incdur))
                lm += [x.pitch.value + 12.*x.pitch.octave for i in range(ndigits)]

        marr = np.array(lm)
        #marr_rel_root  = marr_abs - key.root.value
        #marr_rel_ionian = marr_abs - key.relative_ionian.root.value
        return marr

    def isNote(x):
        return isinstance(x,Note)

    def isBeam(x):
        return isinstance(x,Beam)

    def simplifyTokens(self,tokens):
        '''
        Removes any elements that aren't notes or bars.
        '''
        results = []
        for t in tokens:
            if isNote(t) or isBeam(t):
                results.append(t)
            else:
                pass
        return results

    def findMeasures(self,tokens1):
        '''
        For now this requires that parts be repeating
        '''
        tokens = simplifyTokens(tokens1)
        result = []
        meas = []
        for t in tokens:
            if isBeam(t):
                meas.append(t)
                result.append(meas)
                meas = []
            else:
                meas.append(t)
        return result


    def findParts(self,measures):

        result = []
        part = []
        for m in measures:
            if  ':|' in str(m[-1]):
                part.append(m)
                result.append(part)
                part = []
            else:
                part.append(m)
        return result
    
            

In [26]:
dtune = digitizedTune(tune=tune)

In [27]:
dtune.tune
dtune.part(0)

[array([ 18.,  18.,  18.,  18.,  16.,  16.,  16.,  16.,  14.,  14.,  14.,
         14.,  12.,  12.,  12.,  12.,   9.,   9.,   9.,   9.,   7.,   7.,
          7.,   7.]),
 array([  9.,   9.,   9.,   9.,   9.,   9.,   9.,   9.,  14.,  14.,  14.,
         14.,  12.,  12.,  12.,  12.,   9.,   9.,   9.,   9.,   7.,   7.,
          7.,   7.]),
 array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  2.,  2.,  2.,  2.,  2.,
         2.,  2.,  2.,  4.,  4.,  4.,  4.,  2.,  2.,  2.,  2.]),
 array([ 6.,  6.,  6.,  6.,  4.,  4.,  4.,  4.,  6.,  6.,  6.,  6.,  7.,
         7.,  7.,  7.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.]),
 array([  9.,   9.,   9.,   9.,   7.,   7.,   7.,   7.,   9.,   9.,   9.,
          9.,  12.,  12.,  12.,  12.,   9.,   9.,   9.,   9.,   7.,   7.,
          7.,   7.]),
 array([  9.,   9.,   9.,   9.,   7.,   7.,   7.,   7.,   9.,   9.,   9.,
          9.,  12.,  12.,  12.,  12.,  14.,  14.,  14.,  14.,  16.,  16.,
         16.,  16.]),
 array([ 18.,  18.,  18.,  18.,  16.,  16., 

In [28]:
tune.tokens

[<Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A2">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "F2">,
 <Note "D">,
 <Space " ">,
 <Note "D">,
 <Note "E">,
 <Note "D">,
 <Beam "|">,
 <Space " ">,
 <Note "F">,
 <Note "E">,
 <Note "F">,
 <Space " ">,
 <Note "G">,
 <Note "F">,
 <Note "G">,
 <Beam "|">,
 <Newline "
 ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "G">,
 <Note "A">,
 <Space " ">,
 <Note "c">,
 <Note "d">,
 <Note "e">,
 <Beam "|">,
 <Note "f">,
 <Note "e">,
 <Note "d">,
 <Space " ">,
 <Note "c">,
 <Note "A">,
 <Note "G">,
 <Beam "|">,
 <Space " ">,
 <Note "A">,
 <Note "d">,
 <Note "^c">,
 <Space " ">,
 <Note "d3">,
 <Beam ":|">,
 <Newline "
 ">,
 <Note "f2">,
 <Note "d">,
 <Space " ">,
 <Note "d">,
 <Note "^c">,
 <Note "d">,
 <Beam "|">,
 <Space "

In [29]:
pitch_values

{'A': 9,
 'A#': 10,
 'Ab': 8,
 'B': 11,
 'B#': 12,
 'Bb': 10,
 'C': 0,
 'C#': 1,
 'Cb': -1,
 'D': 2,
 'D#': 3,
 'Db': 1,
 'E': 4,
 'E#': 5,
 'Eb': 3,
 'F': 5,
 'F#': 6,
 'Fb': 4,
 'G': 7,
 'G#': 8,
 'Gb': 6}

In [30]:
note.length

(2, 1)

In [31]:
note.key

<Key D mixolydian>

In [32]:
note.pitch

<Pitch A>

In [33]:
note.pitch

<Pitch A>

In [34]:
note.pitch

<Pitch A>

In [35]:
note.pitch.value

9

In [36]:
note.pitch.pitch_value

<function pyabc.pitch_value>

In [37]:
note.pitch.value

9

In [38]:
note.pitch.octave

0

In [39]:
isinstance?

In [40]:
measures

[[<Note "f">,
  <Note "e">,
  <Note "d">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A2">, <Note "d">, <Note "c">, <Note "A">, <Note "G">, <Beam "|">],
 [<Note "F2">, <Note "D">, <Note "D">, <Note "E">, <Note "D">, <Beam "|">],
 [<Note "F">,
  <Note "E">,
  <Note "F">,
  <Note "G">,
  <Note "F">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">,
  <Note "G">,
  <Note "A">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">,
  <Note "G">,
  <Note "A">,
  <Note "c">,
  <Note "d">,
  <Note "e">,
  <Beam "|">],
 [<Note "f">,
  <Note "e">,
  <Note "d">,
  <Note "c">,
  <Note "A">,
  <Note "G">,
  <Beam "|">],
 [<Note "A">, <Note "d">, <Note "^c">, <Note "d3">, <Beam ":|">],
 [<Note "f2">, <Note "d">, <Note "d">, <Note "^c">, <Note "d">, <Beam "|">],
 [<Note "f2">, <Note "g">, <Note "a">, <Note "g">, <Note "f">, <Beam "|">],
 [<Note "e2">, <Note "c">, <Note "c">, <Note "B">, <Note "c">, <Beam "|">],
 [<Note "e2">, <Note "f">, <Note "g">, <Note "f">, <Note "

In [41]:
parts

[[[<Note "f">,
   <Note "e">,
   <Note "d">,
   <Note "c">,
   <Note "A">,
   <Note "G">,
   <Beam "|">],
  [<Note "A2">, <Note "d">, <Note "c">, <Note "A">, <Note "G">, <Beam "|">],
  [<Note "F2">, <Note "D">, <Note "D">, <Note "E">, <Note "D">, <Beam "|">],
  [<Note "F">,
   <Note "E">,
   <Note "F">,
   <Note "G">,
   <Note "F">,
   <Note "G">,
   <Beam "|">],
  [<Note "A">,
   <Note "G">,
   <Note "A">,
   <Note "c">,
   <Note "A">,
   <Note "G">,
   <Beam "|">],
  [<Note "A">,
   <Note "G">,
   <Note "A">,
   <Note "c">,
   <Note "d">,
   <Note "e">,
   <Beam "|">],
  [<Note "f">,
   <Note "e">,
   <Note "d">,
   <Note "c">,
   <Note "A">,
   <Note "G">,
   <Beam "|">],
  [<Note "A">, <Note "d">, <Note "^c">, <Note "d3">, <Beam ":|">]],
 [[<Note "f2">, <Note "d">, <Note "d">, <Note "^c">, <Note "d">, <Beam "|">],
  [<Note "f2">, <Note "g">, <Note "a">, <Note "g">, <Note "f">, <Beam "|">],
  [<Note "e2">, <Note "c">, <Note "c">, <Note "B">, <Note "c">, <Beam "|">],
  [<Note "e2">, 